name: Update Random Fact
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get random fact
        id: random-fact
        run: |
          # Chiamata HTTP all'API per ottenere un random fact
          FACT=$(curl -s "https://uselessfacts.jsph.pl/api/v2/facts/random" | jq -r '.text')
          echo "fact=${FACT}" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          # Escape caratteri speciali per sed
          ESCAPED_FACT=$(echo "${{ steps.random-fact.outputs.fact }}" | sed 's/[\/&]/\\&/g')
          
          # Aggiorna solo la riga del fatto mantenendo la formattazione
          sed -i -e "/> \[!TIP]/{n;n; s/> .*/> ${ESCAPED_FACT}/}" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🔄 Update random fact" || echo "No changes to commit"
          git push
